/*
MySQL Data Transfer
Source Host: localhost
Source Database: exploremalang
Target Host: localhost
Target Database: exploremalang
Date: 20/04/2016 15:28:36
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for tb_place
-- ----------------------------
CREATE TABLE `tb_place` (
  `idplace` int(3) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `description` text NOT NULL,
  `picture` varchar(50) NOT NULL DEFAULT 'css/img/place/',
  `category` enum('sport','park','recreation','history','nature') NOT NULL DEFAULT 'nature',
  `pricekid` int(10) NOT NULL DEFAULT '0',
  `priceadult` int(10) NOT NULL DEFAULT '0',
  `distance` int(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idplace`)
) ENGINE=InnoDB AUTO_INCREMENT=58 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for tb_profile
-- ----------------------------
CREATE TABLE `tb_profile` (
  `username` varchar(20) NOT NULL,
  `name` varchar(128) NOT NULL,
  `picture` varchar(255) DEFAULT 'css/img/profile/unset.png',
  `sex` enum('P','L') DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `joined` date DEFAULT NULL,
  PRIMARY KEY (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for tb_purchase
-- ----------------------------
CREATE TABLE `tb_purchase` (
  `idpurchase` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(20) NOT NULL,
  `idplace` int(3) NOT NULL,
  `price` int(10) NOT NULL,
  `adult` int(1) NOT NULL DEFAULT '0',
  `kid` int(1) NOT NULL DEFAULT '0',
  `purchased` date NOT NULL,
  `for` date NOT NULL,
  PRIMARY KEY (`idpurchase`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for tb_review
-- ----------------------------
CREATE TABLE `tb_review` (
  `idreview` int(4) NOT NULL AUTO_INCREMENT,
  `username` varchar(20) NOT NULL,
  `idplace` int(3) NOT NULL,
  `review` varchar(255) NOT NULL,
  `rating` enum('5','4','3','2','1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`idreview`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for tb_subscriber
-- ----------------------------
CREATE TABLE `tb_subscriber` (
  `email` varchar(128) NOT NULL,
  PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for tb_user
-- ----------------------------
CREATE TABLE `tb_user` (
  `username` varchar(20) NOT NULL DEFAULT '',
  `password` varchar(32) NOT NULL,
  `email` varchar(254) NOT NULL,
  `level` enum('user','admin') DEFAULT 'user',
  `reset` enum('1','0') DEFAULT '0',
  `verification` enum('1','0') DEFAULT '0',
  `verificationcode` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `tb_place` VALUES ('1', 'Air Terjun Coban Glothak', '<p>Coban ini memiliki ketinggian sekitar 100 m dan berada di lereng Gunung Kawi.  Menurut  masyarakat setempat Coban Glotak ini merupakan coban terakhir dari 7 coban yang berada di atasnya. Tempatnya yang tersembunyi membuat air terjun yang memiliki ketinggian sekitar 100 meter ini belum banyak dikunjungi wisatawan. Suasana alam di sekitarnya juga masih alami.</p><p>Konon, nama Coban Glotak itu berasal dari bunyi bebatuan yang jatuh bersama jatuhnya air terjun. Bebatuan yang jatuh dan di bawa air itu menimbulkan bunyi klotak - klotak.  Kejadian itulah yang kemudian dijadikan nama air terjun tersebut.  Dan hingga saat ini, bebunyian itu masih bisa di dengar saat malam hari tiba.</p>', 'css/img/place/cobanglothak.jpg', 'nature', '0', '0', '20');
INSERT INTO `tb_place` VALUES ('2', 'Air Terjun Coban Pelangi', '<p>Wisata air terjun Coban Pelangi merupakan wisata yang berada di kawasan Desa Gubugklakah, Kecamatan Poncokusumo, Kabupaten Malang. Tepatnya berjarak sekitar 2 km dari Desa Gubugklakah atau sekitar kurang lebih 32 km sebelah timur Kota Malang. Wisata ini sangat menarik. Dinamakan Coban Pelangi karena air terjun ini sering membiaskan warna pelangi. Obyek wisata ini merupakan salah satu wanawisata yang dikelola oleh Perum Perhutani KPH Malang, dan dikelilingi oleh Taman Nasional Bromo Tengger Semeru (TN BTS). Air terjun ini berada di ketinggian 1299,5 m di kaki Gunung Semeru. Suhu udara di kawasan ini berkisar antara 19 â€“ 23 derajat Celcius.</p>', 'css/img/place/cobanpelangi.jpg', 'nature', '5000', '5000', '35');
INSERT INTO `tb_place` VALUES ('3', 'Air Terjun Coban Rais', '<p>Coban Rais memiliki ketinggian terjunan sekitar 20 m dan merupakan salah satu obyek wisata air terjun di kota Batu. Coban ini berada di ketinggian sekitar 1025 m dpl di lereng Gunung Panderman.  Dulunya coban ini bernama Coban Sabrangan yang berarti jika hendak ke coban ini harus menyebrang 14 sungai.</p><p>Pagi hari merupakan waktu terbaik jika ingin mengunjungi tempat wisata ini. Dan sangat tidak disarankan untuk mengunjungi tempat ini saat musim hujan.</p>', 'css/img/place/cobanrais.jpg', 'nature', '5000', '5000', '32');
INSERT INTO `tb_place` VALUES ('4', 'Air Terjun Coban Rondo', '<p>Coban Rondo, Coban adalah air terjun dan Rondo adalah Janda. Air terjun yang indah ini jatuh di lereng Gunung Panderman resor yaitu sekitar 32 km dari barat ke Malang, sangat menarik untuk melihat dan kunjungi.Ketinggian air terjun sekitar 84meter. Pengunjung dapat menemukan dan menikmati keindahan panorama bijih kesan damai di sekitar air terjun.</p>', 'css/img/place/cobanrondo.jpg', 'nature', '10000', '10000', '32');
INSERT INTO `tb_place` VALUES ('5', 'Air Terjun Coban Talun', '<p>Coban Talun wisata air terjun terletak di sub-desa Junggo, Desa Tulungrejo, Bumiaji. Air terjun ini terletak di antara batu-batu besar. Di dasar air terjun terdapat kolam renang air dangkal yang boleh digunakan untuk berenang. Coban Talun juga dikelilingi oleh hutan dan pegunungan yang sejuk. Karena dari keindahan alam tersebut, kawasan ini sering digunakan sebagai kawasan perkemahan. Ground camp ini terletak di satu wilayah dengan air terjun Coban Talun. Alam dan kawasan dingin, membuat banyak pengunjung, baik dari dunia pendidikan dan publik, menarik untuk mengunjungi camp ini.\r\n</p>', 'css/img/place/cobantalun.jpg', 'nature', '5000', '5000', '30');
INSERT INTO `tb_place` VALUES ('6', 'Air Terjun Parang Teja', '<p>Air Terjun Parang Teja memiliki ketinggian sekitar 100 m dengan kucuran air yang halus.  Air terjun ini terletak dilereng Gunung Butak dan membentuk aliran Sungai Metro di perbatasan Desa Tlekung Kecamatan Junrejo Kota Batu dan Kabupaten Blitar.</p><p>Terletak di Kecamatan Dau, Kabupaten Malang. Berjarak sekitar 20 km dari Kota Malang atau 21 km dari Kota Batu.</p>', 'css/img/place/parangteja.jpg', 'nature', '5000', '5000', '20');
INSERT INTO `tb_place` VALUES ('7', 'Alun-Alun Kota Batu', '<p>Semenjak direnovasi dan dibuka kembali pada bulan Mei 2011, Alun-alun Kota Batu menjadi ikon baru pariwisata kota Batu. Alun-alun ini menjadi satu-satunya alun-alun di Indonesia yang memiliki Ferris Wheel atau Bianglala. Selain itu, alun-alun Kota Batu juga dilengkapi dengan berbagai macam fasilitas yang menarik.</p><p>Ditengah-tengah alun-alun terdapat patung apel yang merupakan simbol dari Kota Batu itu sendiri. Alun-Alun Kota Batu juga memiliki sebuah mini playground untuk anak-anak.  Terletak tepat di depan Plaza Batu, tempat ini juga memiliki air mancur di salah satu sudut yang menjadi atraksi tersendiri. Biasanya banyak anak kecil yang bermain basah-basahan di area ini. Selain itu terdapat juga smoking area serta ruang informasi yang berbentuk strawberry raksasa dan toilet dengan bentuk apel besar. Di tengah alun-alun terdapat air mancur yang sangat iconic.</p>', 'css/img/place/alunbatu.jpg', 'park', '0', '0', '22');
INSERT INTO `tb_place` VALUES ('8', 'Alun-Alun Kota Malang', '<p>Merupakan Taman yang Indah dikelilingi oleh bangunan kuno seperti masjid Jami dan gereja Katolik serta pusat perbelanjaan. Alun-alun kini tidak hanya sebagai pusat kota tapi telah menjadi tempat berkunjung warga, maupun wisatawandomestik. Akses teknologi informasi juga mulai merambah Kota Malang di beberapa titik, seperti halnya alun-alun, kini dilengkapi dengan hotspot, yang memungkinkan akses informasi setiap saat. Peremajaan taman kota yang selalu dilakukan pemerintah Kota Malang kian menambah indahnya Kota Malang.</p>', 'css/img/place/alunkota.jpg', 'park', '0', '0', '1');
INSERT INTO `tb_place` VALUES ('9', 'Alun-Alun Tugu Malang', '<p>Alun-Alun Tugu Kota Malang sering juga disebut sebagai Alun-alun Bundar karena memang berbentuk lingkaran. Dibangun pada masa pemerintahan kolonial Belanda, alun-alun ini memiliki sebuah tugu yang berdiri kokoh. Tugu yang menjadi kebanggaan Kota Malang ini dulunya merupakan Taman Gubernur Jendral Hindia Belanda J.P. Zoen Coen.</p><p>Dikelilingi oleh taman berbunga yang sangat indah serta beberapa pohon Trembesi, tepat di bawah tugu terdapat kolam yang penuh dengan bunga teratai yang selalu mekar. Tepat terletak di depan gedung Balai Kota Malang, Alun-Alun Bundar ini kerap menjadi lokasi untuk sesi foto pra-wedding. Tidak heran memang karena keindahan taman alun-alun Tugu ini memang begitu mempesona.</p>', 'css/img/place/aluntugu.jpg', 'park', '0', '0', '1');
INSERT INTO `tb_place` VALUES ('10', 'Araya Golf & Family Club', '<p>Siapa yang tidak kenal Kota Araya, sebuah kota di dalam kota Malang. Ya, perumahan elit ini memang terkenal sebagai kawasan hunian para eksekutif yang juga menawarkan beberapa tempat hiburan, diantaranya yaitu Plaza Araya dan Family Club.</p><p>Terletak di Jalan Lawang Sewu Golf 2-18, Araya Malang, Araya Golf & Family Club ditujukan tidak hanya untuk para warga Kota Araya, tetapi terbuka untuk umum bagi siapa saja yang ingin menikmati hijaunya Kota Araya serta segarnya mandi di kolam renang Araya. Selain golf dan berenang, kita juga dapat melakukan berbagai olahraga lainnya seperti badminton, basket, tenis, serta gym. Araya Golf & Family Club memang lebih menekankan kepada rekreasi kesehatan serta tempat bersantai yang nyaman bagi seluruh anggota keluarga. </p>', 'css/img/place/araya.jpg', 'nature', '25000', '25000', '11');
INSERT INTO `tb_place` VALUES ('11', 'Arena Balap Velodrome', '<p>Arena Balap Velodrome Kota Malang adalah tempat arena balap sepeda (pancal) dengan bangunan melingkar untuk menjadi track balap sepeda. Di halaman luar terdapat arena track untuk balap bmx dengan super bowl dan hambatan offroad lainnya. Di sekeliling bangunan juga terdapat bedak yang biasanya digunakan untuk berjualan buku, komik, novel dan majalah baik yang baru maupun bekas. Pada hari Minggu pagi, tempat ini akan ramai karena terdapat Pasar Minggu yang berderet-deret dengan menjual makanan dan dagangan lainnya.</p>', 'css/img/place/velodrome.jpg', 'sport', '0', '0', '7');
INSERT INTO `tb_place` VALUES ('12', 'Batu Night Spectacular', '<p>Sesuai namanya, wisata ini baru dibuka pada malam hari. Di tempat wisata malam ini, wisatawan bisa menikmati becak yang berjalan seolah di atas awan. Dari becak ini, wisatawan akan merasakan kesejukan udara Kota Batu. Selain itu, wisatawan bisa melihat kilauan Kota Malang. Belum lagi beberapa wahana yang membuat adrenalin wisatawan menjadi naik. Wahana tersebut adalah Flying Swinger dan Galeri Hantu. Bagi anak-anak, BNS merupakan tempat yang menyenangkan. Sebab hampir separuh area BNS merupakan tempat bermain anak-anak. Tidak hanya itu, BNS juga merupakan surga bagi penggemar otomotif dimana terdapat ajang go kart dan Drag Race serta slalom test. Lintasan go kart, slalom test dan drag race yang ada di BNS cukup panjang yaitu sekitar 1 kilometer.</p>', 'css/img/place/bns.jpg', 'recreation', '20000', '20000', '20');
INSERT INTO `tb_place` VALUES ('13', 'Batu Secret Zoo', '<p>Batu Secret Zoo merupakan tempat wisata dan kebun binatang modern yang terletak di Kota Batu, Jawa Timur. Batu Secret Zoo yang berada di tanah seluas 14 hektare tersebut merupakan bagian dari Jatim Park 2, selain Pohon Inn dan Museum Satwa. Beberapa koleksi hewan dari berbagai habitat yang sebagian besar berasal dari Asia dan Afrika dapat ditemukan di kebun binatang ini, antara lain singa putih, kijang afrika, burung macau, dan bermacam-macam reptil.</p><p>Batu Secret Zoo memiliki berbagai jenis dari seluruh belahan dunia, seperti Singa dari Afrika, Gajah dari Sumatra, dan lain sebagainya. Juga terdapat Giant Wheel, Log Flume, Kidz Zone, River Adventure, dan lain-lain sebagai fasilitas dan tempat bermain untuk pengunjung.</p>', 'css/img/place/batusecretzoo.jpg', 'recreation', '75000', '75000', '20');
INSERT INTO `tb_place` VALUES ('14', 'Candi Badut', '<p>Candi Badut terletak di kawasan Tidar, Kota Malang. Dapat ditempuh dengan kendaraan umum jurusan Tidar.  Candi ini diperkirakan berusia lebih dari 1400 tahun dan diyakini adalah peninggalan Prabu Gajayana, penguasa kerajaan Kanjuruhan sebagaimana yang termaktub dalam prasasti Dinoyo bertahun 760 Masehi.</p>\r\n<p>Kata Badut di sini berasal dari bahasa sansekerta â€œBha-dyutâ€ yang berarti sorot Bintang Canopus atau Sorot Agastya. Hal itu terlihat pada ruangan induk candi yang berisi sebuah pasangan arca tidak nyata dari Siwa dan Parwati dalam bentuk lingga dan yoni.</p><p>Candi Badut terletak di kawasan Tidar, Kota Malang. Dapat ditempuh dengan kendaraan umum jurusan Tidar.  Candi ini diperkirakan berusia lebih dari 1400 tahun dan diyakini adalah peninggalan Prabu Gajayana, penguasa kerajaan Kanjuruhan sebagaimana yang termaktub dalam prasasti Dinoyo bertahun 760 Masehi.</p>\r\n<p>Kata Badut di sini berasal dari bahasa sansekerta â€œBha-dyutâ€ yang berarti sorot Bintang Canopus atau Sorot Agastya. Hal itu terlihat pada ruangan induk candi yang berisi sebuah pasangan arca tidak nyata dari Siwa dan Parwati dalam bentuk lingga dan yoni.</p>', 'css/img/place/candibadut.jpg', 'history', '0', '0', '7');
INSERT INTO `tb_place` VALUES ('15', 'Candi Jago', '<p>Candi Jago berasal dari kata â€œJajaghuâ€, didirikan pada masa Kerajaan Singhasari di abad ke-13. Berlokasi di Kecamatan Tumpang, Kabupaten Malang, atau sekitar 22 km dari Kota Malang.</p><p>Candi ini cukup unik, karena bagian atasnya hanya tersisa sebagian dan menurut cerita setempat karena tersambar petir. Relief-relief Kunjarakarna dan Pancatantra dapat ditemui di candi ini. Sengan keseluruhan bangunan candi ini tersusun atas bahan batu andesit.</p>', 'css/img/place/candijago.jpg', 'history', '0', '0', '22');
INSERT INTO `tb_place` VALUES ('16', 'Candi Kidal', '<p>Candi Kidal terletak sekitar 7 Km dari Kecamatan Tumpang tepatnya di Desa Kidal. Candi Kidal ini menghadap Barat, mempunyai tinggi 12,5 meter dan merupakan tempat abu jenazah raja kedua dari Kerajaan Singhasari (1227 â€“ 1248) yaitu Anusapati yang dipuja sebagai Syiwa. Diperkirakan pembangunan candi ini sekitar tahun 1260. Pada dinding candi di sebelah belakang terdapat pahatan-pahatan yang indah dan menggambarkan Garuda sedang membawa Amarta, air kehidupan untuk menebus ibunya yang diperbudak oleh saudaranya.</p>', 'css/img/place/candikidal.jpg', 'history', '0', '0', '17');
INSERT INTO `tb_place` VALUES ('17', 'Candi Singosari', '<p>Kabupaten Malang memiliki banyak sekali peninggalan-peninggalan dari kerajaan-kerajaan di masa lalu. Salah satunya yaitu Candi Singosari atau disebut juga dengan Candi Singhasari. Candi ini terletak di Kecamatan Singosari yang lebih kurang 11 km sebelah utara dari pusat kota Malang. Candi Singosari juga merupakan makam Raja Kertanegara (1268 â€“ 1292) sebagai Bhirawa atau dewa Syiwa dalam bentuk ganas.</p>', 'css/img/place/candisingosari.jpg', 'history', '5000', '3000', '11');
INSERT INTO `tb_place` VALUES ('18', 'Eco Green Park', '<p>Wahana yang bermotto Fun and Study ini berisi tentang ekosistem dan reptil yang lengkap dan bertaraf internasional. Konsepnya memadukan wisata alam, kebudayaan, lingkungan, dan seni yang inspiratif, menarik, serta mendidik. Wisata ini sangat cocok untuk rekreasi keluarga, terutama sebagai wisata edukasi untuk anak-anak. Tujuannya agar anak-anak bisa belajar tentang ekosistem. Banyak manfaat dan pengetahuan bisa didapatkan dari lokasi ini. Pengunjung diajarkan untuk sadar terhadap lingkungan dengan berbagai permainan yang unik dan sangat menyenangkan. Lokasi yang bertetangga dengan Batu Secret Zoo ini menawarkan sekitar 35 wahana edukasi.</p>', 'css/img/place/ecogreenpark.jpg', 'recreation', '30000', '30000', '21');
INSERT INTO `tb_place` VALUES ('19', 'GOR Bima Sakti', '<p>GOR Bima Sakti merupakan gedung olahraga yang digunakan sebagai markas tim basket Bima Sakti. Di dalam gedung olahraga ini terdapat lapangan basket dan juga fasilitas-fasilitas lainnya seperti kamar mandi, dan lain-lain.</p><p>Selain lapangan basket, juga terdapat gedung lapangan futsal yang terletak berseberangan dengan lapangan basket. Di atas lapangan futsal juga terdapat GYM yang biasa digunakan para pemain basket berlatih fisik.</p>', 'css/img/place/bimasakti.jpg', 'sport', '25000', '25000', '2');
INSERT INTO `tb_place` VALUES ('20', 'GOR Ken Arok', '<p>Gedung Olahraga Ken Arok merupakan gedung olahraga serba guna yang terletak di daerah Bululawang, Kabupaten Malang. Bangunan yang didominasi warna hijau, megah, dan menjulang ini biasanya digunakan untuk berlatih basket, voli, dan olahraga lainnya. Tidak hanya untuk sarana olahraga, gedung ini biasanya juga digunakan sebagai tempat untuk acara-acara tertentu.</p>', 'css/img/place/gorkenarok.jpg', 'sport', '0', '0', '6');
INSERT INTO `tb_place` VALUES ('21', 'Gunung Arjuno', '<p>Gunung Arjuno/Arjuna (3.339 mdpl) adalah gunung api yang tidak aktif dan kental dengan suasana mistis, berada \'punggung\' dengan Gunung Welirang (3.156 mdpl) yang masih aktif. Keduanya sering disebut sebagai Arjuno-Welirang.</p><p>Sejak jaman Majapahit, kawasan Arjuno sudah dijadikan sebagai lokasi pemujaan, hal ini dibuktikan dengan banyak ditemukannya bangunan peninggalan sejarah berupa arca maupun candi yang diyakini dari jaman Kerajaan Majapahit. Situs-situs kuno dan bersejarah ini banyak ditemui mulai dari kaki gunung sampai di puncak Arjuno.</p>', 'css/img/place/gunungarjuno.jpg', 'nature', '7500', '7500', '60');
INSERT INTO `tb_place` VALUES ('22', 'Gunung Bromo', '<p>Gunung Bromo (dari bahasa Sanskerta: Brahma, salah seorang Dewa Utama Hindu), merupakan gunung berapi yang masih aktif dan paling terkenal sebagai obyek wisata di Jawa Timur. Sebagai sebuah obyek wisata, Gunung Bromo menjadi menarik karena statusnya sebagai gunung berapi yang masih aktif. Bromo mempunyai ketinggian 2.392 meter di atas permukaan laut itu berada dalam empat wilayah, yakni Kabupaten Probolinggo, Pasuruan, Lumajang, dan Kabupaten Malang. Bentuk tubuh Gunung Bromo bertautan antara lembah dan ngarai dengan kaldera atau lautan pasir seluas sekitar 10 kilometer persegi.</p>', 'css/img/place/bromo.jpg', 'nature', '27500', '27500', '60');
INSERT INTO `tb_place` VALUES ('23', 'Gunung Kawi', '<p>Gunung Kawi, terletak di sebelah barat kota Malang merupakan obyek wisata yang perlu untuk dikunjungi bila kita berada di Jawa Timur karena keunikannya, obyek wisata ini lebih tepat dijuluki sebagai \"kota di pegunungan\". Di sini kita tidak akan menemukan suasana gunung yang sepi, tapi justru kita akan disuguhi sebuah pemandangan mirip di negeri tiongkok zaman dulu.</p><p>Di sepanjang jalan kita akan menemui bangunan bangunan dengan arsitektur khas Tiongkok, dimana terdapat sebuah kuil/klenteng tempat untuk bersembahyang atau melakukan ritual khas Kong Hu Cu. Biasanya orang-orang Tionghoa mengunjungi tempat ini pada hari-hari tertentu untuk melakukan ritual keagamaan seperti memohon keselamatan , giam si , ci suak dsb namun tak jarang pula yang hanya sekedar berpelesir untuk melepas lelah. Di sepanjang jalan juga banyak terdapat penginapan baik itu hotel, losmen, atau bahkan rumah penduduk dapat juga disewa untuk dijadikan tempat menginap.</p>', 'css/img/place/gunungkawi.jpg', 'nature', '3000', '3000', '32');
INSERT INTO `tb_place` VALUES ('24', 'Gunung Panderman', '<p>Gunung Panderman terletak di Toyomerto, Desa Songgokerto, Kota Batu. Gunung Panderman sangat terkenal sebagai objek wisata untuk hiking dan berkemah. Oleh karena itu, tempat ini telah menjadi objek wisata favorit bagi pecinta alam dan petualang. Jika Anda dapat mencapai puncak gunung Panderman, Anda dapat melihat pemandangan alam yang indah dan juga melihat Kota Malang dan Kota Batu dari atas.</p>', 'css/img/place/panderman.jpg', 'nature', '3000', '3000', '28');
INSERT INTO `tb_place` VALUES ('25', 'Gunung Semeru', '<p>Gunung Semeru, adalah sebuah gunung berapi tertinggi di Jawa Timur dan kedua tertinggi se Jawa, tepatnya terletak di Kabupaten Lumajang. Gunung Semeru memiliki ketinggian 3,676 meter di atas permukaan laut dan juga dikenal sebagai Mahameru atau Gunung Agung.</p><p>Nama Semeru berasal dari mitos Hindu-Buddha, yaitu gunung Meru atau Semeru, yang merupakan tempat tinggal para dewa.Gunung Semeru merupakan gunung berapi yang masih sangat aktif dan setiap lebih kurang 20 menit sekali kawahnya mengeluarkan abu vulkanik berwarna hitam dan pasir.</p>', 'css/img/place/semeru.jpg', 'nature', '17500', '17500', '60');
INSERT INTO `tb_place` VALUES ('26', 'Hutan Kota Malabar', '<p>Hutan Kota Malabar ini ada di jalan Malabar, arah timur dari gereja jalan Ijen. Hutan Kota ini luasnya adalah 16.718 meter persegi. Di tengah Hutan Kota Malabar terdapat kolam air yang konon menjadi sumber untuk mengairi taman-taman di kota Malang.</p><p>Begitu masuk ke dalam Hutan Kota Malabar ini, mulai terasa hawa yang sejuk dan terdengar kicauan burung. Hutan Kota Malabar ini sudah mulai lebat pohonnya, sehingga berada di dekatnya pun akan terasa hawa yang segar.</p><p>Sebagai lahan penghijauan yang berlokasi di tengah kota ini, selain sebagai paru-paru kota Malang, Hutan Kota Malabar ini sebenarnya dapat juga dijadikan sebagai alternatif tempat rekreasi yang murah.</p>', 'css/img/place/malabar.jpg', 'nature', '0', '0', '3');
INSERT INTO `tb_place` VALUES ('27', 'Jawa Timur Park I', ' <p>Jawa Timur Park  (Jatim Park) merupakan obyek wisata keluarga di Kota Batu, Malang, yang menawarkan wahana belajar dan rekreasi yang komplit untuk segala usia. Anak-anak sekolah, mulai dari TK hingga SLTA, mahasiswa, dan masyarakat umum pun bisa belajar sambil berekreasi di kawasan Jatim Park. Di dalam obyek wisata yang luasnya sekitar 22 hektar dengan ketinggian 850 meter di atas permukaan laut ini, terdapat wahana taman bermain dan taman belajar yang disertai alat peraga ilmu terapan,seperti biologi, kimia, matemetika, dan fisika. Begitu masuk kawasan taman belajar, pengunjung langsung bisa menyaksikan dan mencoba hasil karya teknologi inovasi pengetahuan dan permainan dari 12 outlet yang luasnya rata-rata 1000 meter persegi.</p>', 'css/img/place/jatimpark1.jpg', 'recreation', '50000', '50000', '25');
INSERT INTO `tb_place` VALUES ('28', 'Kasembon Rafting', '<p>Kasembon rafting mulai dibuka bagi penghobi rafting pada tanggal 9 Desember 2006 oleh Bupati Malang Bapak Sujudi walaupun relatif masih baru sebagai ajang rafting akan tetapi fasilitas-fasilitas penunjang di tempat rafting ini sudah cukup baik. Sebelum berdirinya tempat rafting ini sungai yang akan digunakan untuk tempat rafting ini tidak layak bagi para penghobi rafting karena sepanjang sungainya dipenuhi oleh sampah sehingga kondisinya sangat kotor. Adanya kerjasama yang baik antara Pihak Pemkab, CV. K-land Citra Perdana dan masyarakat dalam membuat fasilitas-fasilitas pendukung buat penghobi olahraga ini dan adanya kepedulian masyarakat sekitar sungai dalam menjaga sungai ini menjadikan sungai ini layak digunakan bagi penghobi rafting.</p>', 'css/img/place/kasembon.jpg', 'sport', '150000', '150000', '3');
INSERT INTO `tb_place` VALUES ('29', 'Kebun Teh Wonosari', '<p>Kebun Teh Wonosari berlokasi di Desa Toyomarto, Kecamatan Singosari, Malang. Untuk menuju ke kebun teh ini akan lebih mudah jika lewat jalur dari Kecamatan Lawang. Kebun teh ini berjarak sekitar 6 km dari Lawang.</p><p>Kebun Teh Wonosari tidak hanya menyediakan wisata alam yang sejuk, tapi juga banyak fasilitas lain yang juga tak kalah seru. Di antaranya adalah Penginapan yang bisa di pesan terlebih dahulu. Lalu ada juga pemandian kolam renang hangat untuk bisa mengusir hawa dingin disana.</p><p>Selain itu ada taman bermain, fasilitas olahraga dan outbound, serta kereta kelinci yang akan membawa anda berkeliling. Selain wisata perkebunan, ada juga wisata di prabik teh itu sendiri. Dan yang pasti terdapat banyak kios makanan yang akan memuaskan anda. </p>', 'css/img/place/kebunteh.jpg', 'nature', '10000', '10000', '26');
INSERT INTO `tb_place` VALUES ('30', 'Kolam Renang Stadion Gajayana', '<p>Dulunya kolam renang gajayana sering disebut \"slembat\", namun seiring berjalannya waktu dan dilakukannya renovasi secara keseluruhan sekitar akhir tahun 2011 lalu, kini resmi berganti nama menjadi Kolam Renang Stadion Gajayana. Kolam Renang Indoor ini mempunyai 2 kolam dengan kedalam yang berbeda yakni kolam untuk anak anak dan kolam untuk orang dewasa dengan kedalaman sekitar 1,5 â€“ 3 meter. Jika Anda pertama kali berkunjung kesini disarankan agar berkunjung sekitar pukul 08.00 â€“ 15.00 WIB. Pasalnya lebih dari jam 3 sore, Kolam Renang Stadion Gajayana akan digunakan khusus untuk para atlit dan klub renang.</p>', 'css/img/place/slembat.jpg', 'sport', '15000', '7000', '2');
INSERT INTO `tb_place` VALUES ('31', 'Lapangan Olahraga Rampal', '<p>Lapangan milik Kodam V/Brawijaya ini memang menjadi tempat jujukan favorit warga yang ingin menikmati sejuknya hawa pagi Malang sambil olah tubuh. Beragam fasilitas olah raga bisa dimanfaatkan di Lapangan Rampal. Sebut saja lapangan basket, lapangan tenis, arena sepak bola, serta jogging track. Beberapa spot pun disediakan khusus untuk area relaksasi serta pemanasan sebelum memulai aktivitas yang lebih berat. Yang terbaik dari semuanya adalah, Lapangan Rampal terbuka untuk umum dan gratis! Anda cukup merogoh kocek untuk membayar karcis parkir pada petugas.</p><p>Di atas tanah seluas kurang lebih 1,5 km2, Lapangan Rampal memang terkesan sangat lega. Tidak banyak struktur yang mengambil tempat, kecuali beberapa fasilitas olah raga dan sebuah tiang bendera berukuran besar. Tidak heran jika seramai apa pun pengunjung, Anda tidak perlu untuk berdesak â€“ desakan.</p>', 'css/img/place/rampal.jpg', 'sport', '0', '0', '3');
INSERT INTO `tb_place` VALUES ('32', 'Masjid Ajaib Turen', '<p>Masjid Ajaib atau juga Masjid Tiban adalah sebenarnya Pondok Pesantren Salafiah Bihaaru Bahri Asali Fadlaailir Rahmah yang terletak di Turen, Kabupaten Malang, Jawa Timur. Pondok Pesantren Salafiah Bihaaru Bahri Asali Fadlaailir Rahmah (Bi Baâ€™a Fadlrah). Nama yang cukup panjang yang mempunyai makna Laut Madu atau, \"Fadilah Rohmat\" (Segarane, Segara, Madune, Fadhole Rohmat-terjemahan Bahasa Jawa).</p><p>Disebut Masjid tiban karena Konon masjid yang sangat megah ini dibangun tanpa sepengetahuan warga sekitar, dan menurut mitos dibangun oleh jin dalam waktu hanya semalam.</p>', 'css/img/place/masjidajaib.jpg', 'history', '0', '0', '27');
INSERT INTO `tb_place` VALUES ('33', 'Merbabu Family Park', '<p>Taman yang berada di Jl. Merbabu, Malang, Jawa Timur ini luasnya mencapai 3.942 meter persegi. Taman tersebut dibuat sebagai bagian dari program Corporate Social Responsibility (CSR) PT Beiersdorf Indonesia melalui bendera NIVEA Cares for Family.</p><p>Taman yang bisa dinikmati publik mulai hari ini Minggu (15/6/2014) memiliki fasilitas untuk seluruh keluarga mulai dari anak-anak hingga lansia. Fasilitas tersebut di antaranya, lapangan mini futsal, jogging track, arena olahraga lansia, arena bermain anak dan taman bacaan.</p><p>Pada area bermain anak, si kecil bisa menikmati ayunan, jungkat-jungkit, perosotan dan bermain pasir di taman ini. Seluruh fasilitas tersebut hadir dalam warna-warna cerah yang menarik perhatian anak.</p>', 'css/img/place/merbabupark.jpg', 'park', '0', '0', '4');
INSERT INTO `tb_place` VALUES ('34', 'Museum Angkut', '<p>Museum Angkut merupakan sebuah tempat wisata baru yang memiliki konsep unik. Dibuka pada tanggal 9 Maret 2014, Museum Angkut menjadi tempat wisata pertama di Asia Tenggara yang mengusung tema transportasi. Museum ini dibangun sebagai tanda apresiasi untuk perkembangan dunia transportasi nusantara dan dunia. Maka tak mengherankan jika di sini Anda bisa menyaksikan berbagai koleksi moda transportasi mulai dari yang masih menggunakan tenaga binatang sampai tenaga listrik.</p><p>Selain mendapatkan informasi mengenai perkembangan dunia transportasi dunia, Anda yang hobi foto juga bisa memuaskan kegemaran Anda di tempat wisata ini. Berbagai landmark buatan yang ada tentunya bisa menjadi latar foto yang menarik. Museum Angkut juga seringkali dijadikan lokasi pameran, event komunitas, kompetisi modifikasi mobil sampai foto prewedding dan pengambilan gambar video klip.</p>', 'css/img/place/museumangkut.jpg', 'recreation', '75000', '50000', '22');
INSERT INTO `tb_place` VALUES ('35', 'Museum Bentoel', '<p>Museum Sejarah Bentoel Malang, salah satu museum yang tidak banyak dikenal orang. Maklum, museum ini baru dibuka untuk publik sejak akhir tahun 2013, setelah melakukan perombakan. Ditambah letakknya yang berada di jalan sempit yang menyebabkan lokasi ini lepas dari perhatian orang yang lalu lalang.</p><p>Mengunjungi museum Bentoel Malang sekarang lebih leluasa, karena dibuka setiap hari dari pukul 08.00 sampai 16.00 WIB, dan gratis tanpa dipungut biaya apapun. Yang diperlukan hanyalah melapor dan mengisi buku tamu di kantor security dekat pintu gerbang masuk. Selanjutnya kita akan diantar Pemandu memasuki ruang demi ruang sambil diberikan penjelasan secara gamblang dan ramah.</p>', 'css/img/place/museumbentoel.jpg', 'history', '0', '0', '1');
INSERT INTO `tb_place` VALUES ('36', 'Museum Brawijaya', '<p>Museum Kota Malang didirikan pada tanggal 4 Mei 1968, resmi disah-kan oleh Purnawirawan Dr. Soewondo. Letak yang cukup strategis membuat Museum Brawijaya lebih mudah dijangkau. Semboyan dari museum Brawijaya Malang adalah \"Citra Uthapana Cakra\". Dari bahasa sansekerta Citra berarti Sinar, Uthapana berarti Yang Membangkitkan, dan Cakra adalah Kekuatan. Berarti jika disatukan arti semboyan tersebut mempunyai makna \"Sinar Yang Membangkitkan Kekuatan\".Untuk pengunjung, Museum Brawijaya Malang terhitung cukup terkenal, mulai dari sabang sampai merauke, bahkan dari luar negeri juga pernah mengunjungi Museum tersebut, diantaranya Australia, Jepang, China, Amerika dan Negara-negara besar lainnya.</p>', 'css/img/place/museumbrawijaya.jpg', 'history', '2000', '2000', '3');
INSERT INTO `tb_place` VALUES ('37', 'Muesum Malang Tempo Doloe', '<p>Museum Tempo Doeloe memang terbilang masih sangat baru. Terletak tidak jauh dari area belakang Balai Kota Malang tepatnya di Jalan Gajah Mada, museum ini diresmikan pada tanggal 22 Oktober 2012 oleh Dwi Cahyono. Ia merupakan pemilik museum sekaligus Ketua Dewan Kesenian Malang serta penggagas Festival Malang Kembali Malang Tempo Doeloe.</p><p>Kondisi luar bangunan yang terkesan modern membuat pengunjung tidak akan mengira kalau di dalamnya terdapat sebuah museum yang unik. Konsep museum ini memang tidak seperti museum kebanyakan di Indonesia. \"New Concept Modern Live Museum\" adalah konsep yang ditawarkan Museum Malang Tempo Doeloe. Berbagai informasi menarik akan kita dapatkan di museum ini. Mulai dari ilmu paleontologi, pra sejarah, sejarah, hingga perang kemerdekaan.</p>', 'css/img/place/museummtd.jpg', 'history', '25000', '10000', '1');
INSERT INTO `tb_place` VALUES ('38', 'Pantai Balekambang', '<p>Pantai Balekambang menawarkan suasana yang berbeda dari resort pantai di bagian Selatan Kota Malang. Pantai ini memiliki tiga pulau dengan jarak sekitar seratus meter, dua di antaranya telah terhubung dengan jembatan ke pantai. Satu dari tiga pulau bernama pulau Ismoyo memiliki candi Hindu, didirikan oleh Hinduists lokal. Setiap tahun, ritual dan upacara tradisional Jalanidhipuja (upacara Hindu) dan Suran (Jawa upacara Tahun Baru) diadakan setiap tahun di sini. Di area parkir terdapat warung, penginapan dan toko suvenir sebagai fasilitas bagi pengunjung. Pantai yang indah ini terletak di desa Srigonco, Bantur kabupaten, sekitar 57 km ke selatan dari Malang dan dapat diakses dengan transportasi umum.</p>', 'css/img/place/balekambang.jpg', 'nature', '5000', '5000', '57');
INSERT INTO `tb_place` VALUES ('39', 'Pantai Goa Cina', '<p>Pantai Goa China adalah sebuah pantai di pesisir selatan yang terletak di Dusun Tumpak Awu, Desa Sitiarjo, Kecamatan Sumbermanjing Wetan, Kabupaten Malang, Jawa Timur. Nama asli pantai ini adalah Pantai Rowo Indah, namun karena pernah terjadi peristiwa kematian seorang China yang sedang bertapa di dalam goa yang ada di kawasan pantai ini, nama Rowo Indah kalah popular daripada Goa China sampai sekarang.</p><p>Selain popular dengan keberadaan goanya, pantai ini juga menyajikan fenomena alam yang langka, yakni terjadinya gelombang bersimpangan tidak keruan dari tiga arah, selatan, timur dan barat. Arus gelombang itu selalu bertabrakan di antara Pulau Bantengan dan Pulau Nyonya. Karena arus gelombang yang bertabrakan demikian kuat, sehingga memunculkan suara bergemuruh. Inilah salah satu fenomena alam yang cukup langka di pantai Malang Selatan.</p>', 'css/img/place/goacina.jpg', 'nature', '5000', '5000', '60');
INSERT INTO `tb_place` VALUES ('40', 'Pantai Sendang Biru', '<p>Pantai Sendang biru terletak 69 km ke arah selatan dari kota Malang. Untuk bisa berkunjung di Pantai Sendang biru ini harus melewati Turen, kemudian Sumbermanjing Wetan. Tempatnya berada di kecamatan Sumber Manjing Wetan. Pantai Sendang biru lebih dikenal sebagai tempat pendaratan dan pelelangan ikan Kabupaten Malang.</p>', 'css/img/place/sendangbiru.jpg', 'nature', '5000', '5000', '69');
INSERT INTO `tb_place` VALUES ('41', 'Paralayang', '<p>Diatas kawasan wisata ini yang tepatnya berlokasi di puncak Gunung Banyak, Anda bisa menemui kawasan yang diperuntukkan untuk olahraga paragliding atau paralayang. Hanya dengan Rp. 250.000 anda bisa menikmati indahnya Kota Batu dari udara dan ini bisa menjadi pengalaman yang luar biasa bagi anda yang memang hobby dengan olahraga ini.</p><p>Selain digunakan untuk olahraga, disaat malam hari tempat ini juga sering dikunjungi karena akan tampak pemandangan indah malam hari dari Kota Batu</p>', 'css/img/place/paralayang.jpg', 'sport', '5000', '5000', '26');
INSERT INTO `tb_place` VALUES ('42', 'Pemandian Air Panas Cangar', '<p>Cangar wisata terletak di desa Tulungrejo, Bumiaji kabupaten. Cangar lain adalah tempat wisata gunung. Cangar juga memiliki sumber air panas kolam renang dengan suhu 30 C â€“ 40 C. Bila berenang disini, juga dapat menyembuhkan penyakit kulit. Pengunjung akan menikmati pemandangan alam di sekelilingnya. Cangar pariwisata memiliki beberapa fasilitas pariwisata yang akan membuat semua pengunjung nyaman untuk mengunjungi kawasan wisata ini, mereka adalah: wisata alam, ground camp, sumber air panas kolam renang, hutan penelitian, balai, dan lain-lain.</p>', 'css/img/place/cangar.jpg', 'nature', '5000', '5000', '16');
INSERT INTO `tb_place` VALUES ('43', 'Pemandian Selecta', '<p>Pemandian Selecta terletak di Desa Tulungrejo, Kota Batu, Jawa Timur dengan dikelilingi oleh Gunung Arjuno, Welirang dan Anjasmoro, dapat ditempuh dalam waktu 1 jam dari kota Malang dan 2 jam dari kota Surabaya. Tinggi dari permukaan laut 1.150 m dengan suhu udara berkisar antara 15 derajat C â€“ 25 derajat C dan kedinginan air berkisar 18 derajat C. Wista ini menyajikan pemandian air dingin dan juga air panas. Terdapat juga Pasar Wisata Selecta yang merupakan tempat ideal untuk berbelanja, yang menyediakan berbagai macam tanaman hias, suvenir, makanan ringan khas Batu dan buahâ€“buahan bahkan kelinci ataupun hewan piaraan yang lain.</p>', 'css/img/place/selecta.jpg', 'recreation', '15000', '15000', '21');
INSERT INTO `tb_place` VALUES ('44', 'Perpustakaan Umum Kota Malang', '<p>Kota Malang memiliki perpustakaan umum yang cukup lengkap koleksi bukunya. Koleksi bukunya mulai dari komik, novel terjemahan, sastra, majalah, buku-buku berbahasa asing dan berbahasa daerah juga tersedia. </p><p>Bangunan perpustakaan memiliki tiga lantai, lantai pertama ada lobby, tempat penyimpanan barang pengunjun, tempat baca Koran, berbagai etalase, tempat fotocopy, tempat pertunjukan, ruang pameran, dan ruangan khusus bacaan anak- anak.</p><p>Ruang baca dan koleksi umum ada di lantai dua, tempat ini menjadi tempat tujuan sebagian besar pengunjung, tempat berbagai buku dari berbagai genre disusun rapi dalam rak-rak panjang. Anda juga dapat mengakses internet secara gratis, atau Anda dapat membawa laptop sendiri. Lantai teratas bagununan ini difungsikan sebagai studio salah satu stasiun televisi swasta di Malang, Mahameru TV.</p>', 'css/img/place/perpustakaan.jpg', 'history', '0', '0', '4');
INSERT INTO `tb_place` VALUES ('45', 'Omah Kayu', '<p>Di sini Anda bisa merasakan sensasi seru menginap di hotel yang didirikan atas sebuah pohon. Apalagi pohon-pohon itu berada di atas ketinggian di atas 1.000 meter di atas permukaan laut. Rumah Pohon atau akrab dengan nama Omah Kayu ini berada di Gunung Banyak tepatnya di lokasi paralayang Kota Wisata Batu. Lokasinya sekitar 25 km dari Kota Malang, dan cukup dekat dari destinasi wisata lainnya di Kota Batu. Dari Alun-alun Kota Batu, Jatim Park I, dan Agro Kusuma hanya sekitar 15 menit. Atau hanya sekitar 6 menit perjalanan dari Songgoriti.</p><p>Omah Kayu sangat cocok untuk digunakan orang yang membutuhkan inspirasi atau ingin merasakan suasana alam.  Pada malam hari kelap kelip lampunya seperti hamparan permata, suara alamnya luar biasa. Apalagi jika tepat pada bulan purnama, pemandangannya sangat indah.</p>', 'css/img/place/omahkayu.jpg', 'recreation', '5000', '5000', '25');
INSERT INTO `tb_place` VALUES ('46', 'Stadion Gajayana', '<p>Stadion Gajayana adalah sebuah stadion serbaguna yang terletak di Kota Malang, Jawa Timur, Indonesia. Stadion Gajayana ini adalah salah satu Stadion tertua di Indonesia.</p><p>Stadion Gajayana yang baru telah berkapasitas kurang lebih 35.000 penonton. Stadion ini merupakan markas dari dua kesebelasan asal Malang, yakni Persema Malang dan Arema Indonesia (sebagai markas kedua).</p>', 'css/img/place/gajayana.jpg', 'sport', '25000', '25000', '2');
INSERT INTO `tb_place` VALUES ('47', 'Stadion Kanjuruhan', '<p>Stadion Kanjuruhan adalah sebuah stadion sepak bola yang terletak di Kepanjen, Malang, Jawa Timur, Indonesia. Kapasitasnya berjumlah kurang lebih 40.000 tempat duduk. Stadion ini merupakan markas kesebelasan sepak bola asal daerah Malang, yakni Arema Indonesia.</p><p>Sejak 2004, Arema Indonesia lebih sering tampil di Stadion Kanjuruhan, karena selain kapasitas stadion yang lebih besar, Kanjuruhan juga tidak berada di pusat kota, sehingga tidak menimbulkan kemacetan ketika Arema bertanding.</p>', 'css/img/place/stadionkanjuruhan.jpg', 'sport', '30000', '30000', '25');
INSERT INTO `tb_place` VALUES ('48', 'Taman Bentoel Trunojoyo', '<p>Taman Bentoel Trunojoyo adalah taman terbuka yang berlokasi strategis di tengah kota, tepat di depan Stasiun Kota Baru. Taman Bentoel Trunojoyo adalah wujud baru dari Taman Trunojoyo lama. Sangat mudah diakses dengan menggunakan angkutan umum.Untuk sementara terdapat dua gerbang di area tersebut, kita akan disambut sebuah gazebo putih bergaya urban di tengah-tengah taman. Banyak pengunjung baik warga sekitar yang ingin bersantai, wisatawan luar kota ataupun para penumpang Kereta Api yang hanya ingin rehat sebelum atau sesudah perjalanan tampak berlama-lama di gazebo ini.</p>', 'css/img/place/tamanbentoel.jpg', 'park', '0', '0', '2');
INSERT INTO `tb_place` VALUES ('49', 'Taman Kridha Budaya Jawa Timur', '<p>Taman Krida Budaya Jawa Timur merupakan tempat khusus untuk apresiasi budaya Jawa Timur. Di sini sering ditampilkan beragam seni Jawa Timur seperti ketoprak, wayang kulit, wayang orang, sendra tari, kuda lumping hingga reog. Selain itu, wisatawan juga bisa menyaksikan kesenian baru yang bernama Bantengan. Kesenian ini merupakan kesenian hasil kreatifitas dari masyarakat Malang. Selain berfungsi sebagai tempat wisata budaya, Taman Krida Budaya Jawa Timur juga tergolong sebagai taman kota. Di bagian dalam taman, pengunjung akan melihat deretan tanaman-tanaman dan pohon-pohonan yang tertata rapi. Di sini Anda juga akan menyaksikan struktur candi. Kegiatan pameran seni juga kerap diselenggarakan di sini.</p><p>Tempat wisata ini memang terbuka untuk umum dan dapat dikunjungi setiap hari kerja. Namun jika Anda ingin melihat sesuatu yang lebih, sebaiknya kunjungi Taman Krida Budaya Jawa Timur pada saat ada perayaan hari besar. Pada moment-moment tersebut, Anda bisa menyaksikan pergelaran bentengan dan kesenian lainnya.</p>', 'css/img/place/kridhabudaya.jpg', 'park', '0', '0', '8');
INSERT INTO `tb_place` VALUES ('50', 'Taman Rekreasi Kota Malang', '<p>Taman Rekreasi Kota (Tarekot), terletak di tengah Kota Malang yaitu di Jl. Simpang Majapahit, tepatnya di belakang Gedung Balaikota Malang, Dibangun pada tahun 2002, Taman Rekreasi Kota Malang adalah untuk memenuhi keinginan masyarakat akan sarana rekreasi atau tempat bermain anak-anak di tengah kota yang memadai dan terjangkau.Taman Rekreasi Kota Malang memiliki fasilitas antara lain: jogging track, kolam renang, area senam bersama, hotspot area, tanaman (flora), taman mini satwa (fauna), stand produk unggulan, stand gasebo (makanan khas malang) dan sarana/tempat bermain anak-anak.</p>', 'css/img/place/tarekot.jpg', 'recreation', '3500', '2000', '1');
INSERT INTO `tb_place` VALUES ('51', 'Taman Rekreasi Lembah Dieng', '<p>Kawasan Objek Wisata Lembah Dieng adalah salah satu objek wisata di kota Malang, Jawa Timur yang paling banyak dikunjungi di kota Malang. Wisata ini menawarkan kolam renang bertaraf internasional dengan harga yang terjangkau.</p><p>Ketika objek Wisata Lembah Dieng Suasananya terasa sejuk, jauh dari kebisingan orang dan kendaraan. Lokasinya hanya lima kilometer dari pusat Kota Malang. Jika ditempuh dengan berkendaraan, sekitar 7 menit dari Alun-alun Kota Malang.</p><p>Di kompleks ini, disediakan tempat refreshing, yang disebut orang dengan Club House Istana Dieng. Di sana juga dilengkapi sarana olahraga seperti Lapanngan tennis, fitness center, kolam renang, arena bowling, dan billiard yang bisa dipergunakan setiap saat. Lebih dari itu, sirkuit gokart pun tersedia.</p><p>Pengunjung juga dapat menikmati sajian spesial yang disediakan di sekitar Pesona Club House Dieng. Disamping itu Taman Wisata Lembah Dieng juga menyediakan area pemancingan, bagi penghobi mancing di kota malang dapat menyalurkan hobinya di tempat wisata ini.</p>', 'css/img/place/lembahdieng.jpg', 'recreation', '15000', '15000', '5');
INSERT INTO `tb_place` VALUES ('52', 'Taman Rekreasi Senaputra', '<p>Berada di Jl Belakang Rumah sakit merupakan sarana hiburan anak-anak dan dewasa,di lengkapi dengan arena bermain dan kolam renang.Di setiap Minggu pagi di pentaskan hiburan Tari Jaran Kepang dan band.Juga merupakan tempat latihan tari, pencak silat dan karate.Terletak hanya 500 meter dari pusat kota.</p>', 'css/img/place/senaputra.jpg', 'recreation', '6000', '6000', '1');
INSERT INTO `tb_place` VALUES ('53', 'Taman Rekreasi Sengkaling', '<p>Taman rekreasi Sengkaling dilengkapi dengan kolam renang standar internasional. Sebagaimana tempat rekreasi keluarga, tempat  ini juga terdapat kolam khusus untuk anak-anak.Semua kolam renang di tempat Rekreasi Sengkaling diisi dengan air sumber yang jernih dan menyegarkan.Bukan hanya kolam renang saja yang disajikan di tempat rekreasi Sengkaling,ada juga danau buatan yang berpanorama indah dengan penuh pepohonan rindang di sekitarnya. Jika anda ingin menikmati danau ini, anda dapat bersantai mengelilinginya dengan mempergunakan sepeda air atau perahu dayung.Baraneka ragam permainan dan rumah makan juga banyak terdapat di taman rekreasi ini. Dan setiap hari Sabtu dan Minggu,taman rekreasi ini menyediakan kolam renang dengan air panas.</p>', 'css/img/place/sengkaling.jpg', 'recreation', '30000', '25000', '12');
INSERT INTO `tb_place` VALUES ('54', 'Taman Singha Merjosari', '<p>Taman Singha Merjosari, terletak di Jl. Mertojoyo Selatan, Kelurahan Merjosari Kecamatan Lowok Waru. Saat ini, taman yang berada di depan Pasar Dinoyo Baru masih dalam tahap penyempurnaan pembangunan. Meskipun demikian Taman Singha Merjosari sudah menorehkan prestasi sebagai taman kota dengan desain terbaik se-Indonesia.</p><p>Taman Singha Merjosari saat ini telah memiliki beragam fasilitas seperti gazebo, playground, area pasir pantai, jogging track, open theater, foot therapy, tanaman langka, parkir sepeda dan toilet. Bahkan untuk menambah kenyamanan pengunjung, disediakan juga air siap minum yang bisa diambil langsung dari kran.</p>', 'css/img/place/tamansinga.jpg', 'park', '0', '0', '7');
INSERT INTO `tb_place` VALUES ('55', 'Taman Wisata Tlogomas', '<p>Taman Rekreasi Tlogomas merupakan taman rekreasi tertua di Malang yang terletak di Jalan Baiduri Pandan, Tlogomas.  Taman rekreasi yang didirikan pada tahun 1989 ini dilengkapi dengan kolam renang dan arena bermain untuk anak-anak. Memasuki kawasan ini, yang terlihat pertama kali adalah suasana asri karena terdapat banyak pohon rindang. Begitu sampai di pintu masuk taman, wisatawan akan menjumpai replika naga yang unik. Replika ular naga tersebut dibuat sedemikian rupa seolah menerobos beberapa permukaan lantai lokasi wisata ini hingga terlihat pecah. Hal ini membuat Taman Rekreasi Tlogomas terlihat futuristik dan mempunyai nilai seni tinggi.</p><p>Kolam renang yang ada di Taman Rekreasi Tlogomas berbeda dengan kolam renang lainnya di Malang. Salah satu kelebihan dari kolam renang di tempat ini yaitu airnya yang selalu jernih, dikarenakan air yang dipakai adalah air dari sumber terdekat. Ada tiga kolam yang disediakan, dua untuk anak-anak dan satu untuk dewasa. Masing-masing kolam renang tersebut berukuran 40 cm, 60 cm, dan 3.5 m.  Kolam renang ini tak pernah sepi pengunjung, khususnya kolam untuk anak-anak. Sejuknya kolam yang berpadu dengan rindangnya pepohonan serta suara aliran Sungai Brantas yang alami dapat membuat rileks para pengunjung. Wisatawan yang sedang menikmati kolam ini dijamin akan betah berlama-lama di sini.</p>', 'css/img/place/tlogomas.jpg', 'recreation', '15000', '15000', '8');
INSERT INTO `tb_place` VALUES ('56', 'Taman Wisata Wendit', '<p>Taman Wisata Wendit terletak di Desa Mangliawan, Kecamatan Pakis, Kabupaten Malang sekitar 8 km dari pusat Kota Malang. Mata air Wendit merupakan salah satu sumber air bagi PDAM Kota Malang. Lokasi wisata alam yang dipadu dengan wisata buatan dan menempati lahan seluas 9 hektar ini memiliki beberapa prototipe diantaranya untuk wisata olahraga air, sejarah, pendidikan dan konservasi hutan kota.</p><p>Daya tarik yang khas obyek wisata ini adalah adanya puluhan kera yang jinak dan bebas berkeliaran di hutan kecil dan menghuni di pepohonannya. Pengunjung bisa memberikan makanan kepada monyet-monyet tersebut. Di Wendit, pengunjung juga bisa menikmati telaga dengan perahu kayu untuk berkeliling. Di sekitar telaga terdapat restoran dan beberapa pondok wisata. Kera-kera jinak dibiarkan lepas mendekati pengunjung menjadi daya tarik di sekitar telaga ini.</p>', 'css/img/place/wendit.jpg', 'recreation', '10000', '5000', '8');
INSERT INTO `tb_place` VALUES ('57', 'Waduk Selorejo', '<p>Wisata  Selorejo terdapat di ke tinggian 600 mdpl, sehingga akan terasa sejuk. Pemandangan Waduk Selorejo juga indah dikarenakan dikelilingi oleh gunung-gunung diantaranya Gunung Kelud, Gunung Anjasmoro serta Gunung Kawi. Berdiri di pinggiran waduk dengan menikmati panorama waduk dengan latar pegunungan yang diselimuti awan sungguh adalah kesenangan tersendiri untuk pengunjung obyek wisata Selorejo. Sambil melihat nelayan sekitar menjaring ikan di bendungan. Bagi mereka yang hobi memancing obyek Wisata Selorejo juga menjadi tujuan utama karena ikannya disini terkenal besar-besar . Yang paling dominan jenis ikan yang ada di Bendungan Selorejo adalah ikan Mujair/ Mujaer.</p><p>Di obyek wisata Selorejo, banyak perahu- perahu yang di sewakan pagi pengunjungnya, menyeberang ke bagian utara bendungan, ke arah Ngantang bagian utara. Di sela-sela menikmati naik perahu tersebut anda bisa melihat kebun Jambu yang cukup luas. Singgah di Kebun jambu dan nikmati sensasi petik buah jambu langsung dari kebunnya.</p>', 'css/img/place/selorejo.jpg', 'recreation', '25000', '20000', '48');
INSERT INTO `tb_profile` VALUES ('admin', 'Administrator', 'css/img/profile/administrator.png', 'L', 'Explore Malang', '2016-04-13');
INSERT INTO `tb_profile` VALUES ('danangbayu', 'danang', 'css/img/profile/unset.png', null, null, '2016-04-18');
INSERT INTO `tb_profile` VALUES ('difa', 'Difa Sanditya', 'css/img/profile/unset.png', null, null, '2016-04-20');
INSERT INTO `tb_profile` VALUES ('difasanditya', 'Difa Sanditya', 'css/img/profile/difasanditya.jpg', 'L', 'Nukus', '2016-04-07');
INSERT INTO `tb_purchase` VALUES ('7', 'difasanditya', '4', '60000', '3', '3', '2016-04-18', '2016-04-30');
INSERT INTO `tb_review` VALUES ('22', 'difasanditya', '2', 'Sempatkanlah diri Anda untuk datang ke tempat ini, karena tempat ini memiliki segala keindahan di muka bumi ini.', '5');
INSERT INTO `tb_review` VALUES ('25', 'difasanditya', '1', 'ertfyuhijjhgv', '4');
INSERT INTO `tb_subscriber` VALUES ('admin@exploremalang.id');
INSERT INTO `tb_subscriber` VALUES ('asd@as.');
INSERT INTO `tb_user` VALUES ('admin', '200ceb26807d6bf99fd6f4f0d1ca54d4', 'admin@exploremalang.id', 'admin', '0', '1', '');
INSERT INTO `tb_user` VALUES ('danangbayu', '5191f88da296a04093c1afa9692d5207', 'danang824@gmail.com', 'user', '0', '1', 'Xh9tCXQxzNuY1C4oJM4SS7q1cYDVUbEa');
INSERT INTO `tb_user` VALUES ('difa', '25d55ad283aa400af464c76d713c07ad', 'difasanditya@gmail.com', 'user', '0', '0', 'aSdMefs8JXfJhHW3XIn4mITezUlwc13o');
INSERT INTO `tb_user` VALUES ('difasanditya', '25d55ad283aa400af464c76d713c07ad', '7i10difa@gmail.com', 'user', '0', '1', 'SZYzuPskqnmIhk3b8VlIASCLKpFkbfSR');
